//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class 时钟
{
	public virtual object 秒
	{
		get;
		set;
	}

	public virtual object 分
	{
		get;
		set;
	}

	public virtual object 时
	{
		get;
		set;
	}

	public virtual void 展示()
	{
		throw new System.NotImplementedException();
	}

	public virtual void 自增()
	{
		throw new System.NotImplementedException();
	}

	public virtual void 自减()
	{
		throw new System.NotImplementedException();
	}

	public virtual void 设置()
	{
		throw new System.NotImplementedException();
	}

}

